import streamlit as st
import torch
import torch.nn as nn
from torchvision import transforms
from PIL import Image

# --------------------------------------------------
# PAGE CONFIG
# --------------------------------------------------

st.set_page_config(
    page_title="Klinefelter Detection System",
    page_icon="🧬",
    layout="centered"
)

# --------------------------------------------------
# MODEL
# --------------------------------------------------

class KlinefelterCNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv = nn.Sequential(
            nn.Conv2d(3, 16, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(16, 32, 3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.fc = nn.Sequential(
            nn.Linear(32 * 32 * 32, 128),
            nn.ReLU(),
            nn.Linear(128, 2)
        )

    def forward(self, x):
        x = self.conv(x)
        x = x.view(x.size(0), -1)
        return self.fc(x)

# --------------------------------------------------
# LOAD MODEL
# --------------------------------------------------

model = KlinefelterCNN()
model.load_state_dict(torch.load("model.pth", map_location=torch.device("cpu")))
model.eval()

# --------------------------------------------------
# IMAGE TRANSFORM
# --------------------------------------------------

transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor()
])

# --------------------------------------------------
# HEADER
# --------------------------------------------------

st.markdown(
    """
    <h1 style='text-align:center;color:#1E88E5;'>
    🧬 AI-Based Klinefelter Syndrome Detection System
    </h1>
    """,
    unsafe_allow_html=True
)

st.success(
    "Deep Learning Powered Genetic Analysis using Convolutional Neural Networks (CNN)"
)

st.divider()

# --------------------------------------------------
# FILE UPLOAD
# --------------------------------------------------

uploaded_file = st.file_uploader(
    "📤 Upload Karyotype Image",
    type=["jpg", "jpeg", "png"]
)

# --------------------------------------------------
# PREDICTION
# --------------------------------------------------

if uploaded_file is not None:

    image = Image.open(uploaded_file).convert("RGB")

    col1, col2 = st.columns([2, 1])

    with col1:
        st.subheader("🖼 Uploaded Image")
        st.image(image, use_container_width=True)

    img = transform(image).unsqueeze(0)

    with torch.no_grad():
        output = model(img)
        probabilities = torch.softmax(output, dim=1)
        confidence, pred = torch.max(probabilities, 1)

    with col2:

        st.subheader("🔍 Prediction")

        if pred.item() == 0:
            result = "Klinefelter Syndrome Detected"
            status = "Positive"
            st.error("⚠️ Klinefelter Syndrome Detected")
        else:
            result = "Normal Karyotype"
            status = "Negative"
            st.success("✅ Normal Karyotype")

        st.markdown("### 🎯 Confidence")

        st.markdown(
            f"""
            <h1 style='color:#1E88E5;'>
            {confidence.item()*100:.2f}%
            </h1>
            """,
            unsafe_allow_html=True
        )

        st.progress(float(confidence.item()))

        report = f"""
AI-BASED KLINEFELTER SYNDROME DETECTION REPORT

-----------------------------------------
Detection Result:
{result}

Confidence Score:
{confidence.item()*100:.2f}%

Status:
{status}

-----------------------------------------
Generated By:
AI-Based Genetic Disorder Detection System
-----------------------------------------
"""

        st.download_button(
            label="📄 Download Report",
            data=report,
            file_name="Klinefelter_Report.txt",
            mime="text/plain"
        )

# --------------------------------------------------
# ABOUT PROJECT
# --------------------------------------------------

st.divider()

with st.expander("ℹ️ About This Project"):

    st.write("""
    This project uses Deep Learning and Convolutional
    Neural Networks (CNN) to classify chromosome
    karyotype images into:

    • Normal Karyotype

    • Klinefelter Syndrome (47,XXY)

    The uploaded image is analyzed and the system
    predicts whether the chromosome pattern is normal
    or affected by Klinefelter Syndrome.
    """)

# --------------------------------------------------
# FOOTER
# --------------------------------------------------

st.divider()

st.caption(
    "🧬 Developed using PyTorch, Streamlit and Deep Learning"
)